spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_multitenant?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=Samridhi
spring.datasource.password=Sa@050605
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ---------------- Swagger/OpenAPI ----------------
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# ---------------- Keycloak (placeholder) ----------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/ecommerce